CREATE TABLE `clients` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`middle_name` text,
	`preferred_name` text,
	`address` text,
	`primary_phone` text,
	`date_of_birth` text,
	`age` integer,
	`photo_path` text,
	`estimated_delivery_date` text,
	`actual_delivery_date` text,
	`gravida` integer,
	`parity` integer,
	`blood_type` text,
	`rh_status` text,
	`gbs_status` text,
	`delivery_method` text,
	`tear_degree` integer,
	`risk_factors` text,
	`partner_name` text,
	`partner_relationship` text,
	`partner_phone` text,
	`partner_blood_type` text,
	`is_active` integer DEFAULT 1 NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	CONSTRAINT "clients_blood_type_check" CHECK("clients"."blood_type" IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
	CONSTRAINT "clients_rh_status_check" CHECK("clients"."rh_status" IN ('+', '-')),
	CONSTRAINT "clients_gbs_status_check" CHECK("clients"."gbs_status" IN ('+', '-')),
	CONSTRAINT "clients_delivery_method_check" CHECK("clients"."delivery_method" IN ('SVD', 'AVD', 'C-Section')),
	CONSTRAINT "clients_tear_degree_check" CHECK("clients"."tear_degree" IN (1, 2, 3, 4)),
	CONSTRAINT "clients_partner_blood_type_check" CHECK("clients"."partner_blood_type" IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
	CONSTRAINT "clients_is_active_check" CHECK("clients"."is_active" IN (0, 1))
);
