// Generated by scripts/generate-migrations-manifest.mjs. Do not edit manually.
import journal from "./meta/_journal.json";
import m0000 from "./0000_many_iron_man.sql";

export default {
  journal,
  migrations: {
    m0000,
  },
};
