// Generated by scripts/generate-migrations-manifest.mjs. Do not edit manually.
import journal from "./meta/_journal.json";
import m0000 from "./0000_many_iron_man.sql";
import m0001 from "./0001_green_praxagora.sql";
import m0002 from "./0002_curly_zaladane.sql";

export default {
  journal,
  migrations: {
    m0000,
    m0001,
    m0002,
  },
};
