import { clients } from "../../src/db/schema";

import type { SeedDatabase } from ".";

export const clientSeedData = [
  {
    firstName: "Maya",
    lastName: "Chen",
  },
  {
    firstName: "Olivia",
    lastName: "Martin",
    middleName: "Rose",
    preferredName: "Liv",
    address: "18 Cedar Lane, Toronto, ON",
    primaryPhone: "416-555-0102",
    dateOfBirth: "1994-08-12",
  },
  {
    firstName: "Amina",
    lastName: "Yusuf",
    address: "72 Willow Street, Toronto, ON",
    primaryPhone: "647-555-0134",
    dateOfBirth: "1990-03-24",
    estimatedDeliveryDate: "2026-10-18",
    gravida: 2,
    parity: 1,
    bloodType: "O+",
    rhStatus: "+",
    gbsStatus: "-",
    riskFactors: "History of gestational hypertension",
    partnerName: "Samir Yusuf",
    partnerRelationship: "Spouse",
    partnerPhone: "647-555-0135",
    partnerBloodType: "A+",
  },
  {
    firstName: "Elena",
    lastName: "Rodriguez",
    preferredName: "Ellie",
    primaryPhone: "416-555-0168",
    dateOfBirth: "1988-11-06",
    estimatedDeliveryDate: "2026-06-05",
    actualDeliveryDate: "2026-06-02",
    gravida: 3,
    parity: 2,
    bloodType: "A+",
    rhStatus: "+",
    gbsStatus: "+",
    deliveryMethod: "SVD",
    tearDegree: 2,
    riskFactors: "GBS positive",
    partnerName: "Marco Rodriguez",
    partnerRelationship: "Spouse",
    partnerPhone: "416-555-0169",
  },
  {
    firstName: "Nora",
    lastName: "Singh",
    dateOfBirth: "1985-01-19",
    estimatedDeliveryDate: "2026-04-27",
    actualDeliveryDate: "2026-04-20",
    gravida: 1,
    parity: 1,
    bloodType: "B-",
    rhStatus: "-",
    deliveryMethod: "C-Section",
    riskFactors: "Breech presentation",
  },
  {
    firstName: "Grace",
    lastName: "Thompson",
    primaryPhone: "905-555-0191",
    estimatedDeliveryDate: "2026-12-09",
    gravida: 4,
    parity: 2,
    isActive: 0,
  },
  {
    firstName: "Priya",
    lastName: "Patel",
    preferredName: "Pri",
    age: 31,
    primaryPhone: "647-555-0117",
    estimatedDeliveryDate: "2027-01-14",
    bloodType: "A-",
    rhStatus: "-",
    partnerName: "Dev Patel",
    partnerRelationship: "Partner",
  },
  {
    firstName: "Claire",
    lastName: "Bennett",
    address: "204 Birch Avenue, Mississauga, ON",
    dateOfBirth: "1992-05-30",
    estimatedDeliveryDate: "2026-03-12",
    actualDeliveryDate: "2026-03-13",
    gravida: 2,
    parity: 2,
    bloodType: "AB+",
    rhStatus: "+",
    gbsStatus: "-",
    deliveryMethod: "AVD",
    tearDegree: 3,
    partnerPhone: "905-555-0144",
    partnerBloodType: "O-",
  },
] satisfies (typeof clients.$inferInsert)[];

/** Inserts fictional clients ranging from minimal records to complete care histories. */
export async function seedClients(db: SeedDatabase): Promise<void> {
  await db.insert(clients).values(clientSeedData);
}
